
var f;f||(f=typeof Module !== 'undefined' ? Module : {});var k={},l;for(l in f)f.hasOwnProperty(l)&&(k[l]=f[l]);var r=[],aa="./this.program";function t(a,b){throw b;}var u=!1,v=!1,ba=!1,ca=!1;u="object"===typeof window;v="function"===typeof importScripts;ba="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node;ca=!u&&!ba&&!v;var w="",da,x,ea,fa;
if(ba)w=v?require("path").dirname(w)+"/":__dirname+"/",da=function(a,b){ea||(ea=require("fs"));fa||(fa=require("path"));a=fa.normalize(a);return ea.readFileSync(a,b?null:"utf8")},x=function(a){a=da(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(aa=process.argv[1].replace(/\\/g,"/")),r=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=f),process.on("uncaughtException",function(a){if(!(a instanceof ha))throw a;}),process.on("unhandledRejection",
y),t=function(a){process.exit(a)},f.inspect=function(){return"[Emscripten Module object]"};else if(ca)"undefined"!=typeof read&&(da=function(a){return read(a)}),x=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?r=scriptArgs:"undefined"!=typeof arguments&&(r=arguments),"function"===typeof quit&&(t=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&
(console={}),console.log=print,console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(u||v)v?w=self.location.href:"undefined"!==typeof document&&document.currentScript&&(w=document.currentScript.src),w=0!==w.indexOf("blob:")?w.substr(0,w.lastIndexOf("/")+1):"",da=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},v&&(x=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var ia=f.print||console.log.bind(console),A=f.printErr||console.warn.bind(console);for(l in k)k.hasOwnProperty(l)&&(f[l]=k[l]);k=null;f.arguments&&(r=f.arguments);f.thisProgram&&(aa=f.thisProgram);f.quit&&(t=f.quit);var B;f.wasmBinary&&(B=f.wasmBinary);var noExitRuntime;f.noExitRuntime&&(noExitRuntime=f.noExitRuntime);"object"!==typeof WebAssembly&&y("no native wasm support detected");var ja,ka=!1;function assert(a,b){a||y("Assertion failed: "+b)}
function la(){var a=f.__sapp_emsc_onpaste;assert(a,"Cannot call unknown function _sapp_emsc_onpaste, make sure it is exported");return a}function ma(a){var b=["string"],c={string:function(n){var q=0;if(null!==n&&void 0!==n&&0!==n){var p=(n.length<<2)+1;q=C(p);D(n,E,q,p)}return q},array:function(n){var q=C(n.length);na.set(n,q);return q}},d=la(),e=[],h=0;if(a)for(var g=0;g<a.length;g++){var m=c[b[g]];m?(0===h&&(h=oa()),e[g]=m(a[g])):e[g]=a[g]}d.apply(null,e);0!==h&&pa(h)}
var qa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function ra(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&qa)return qa.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var h=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|h);else{var g=a[b++]&63;e=224==(e&240)?(e&15)<<12|h<<6|g:(e&7)<<18|h<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?ra(E,a,b):""}
function D(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var h=0;h<a.length;++h){var g=a.charCodeAt(h);if(55296<=g&&57343>=g){var m=a.charCodeAt(++h);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(c>=d)break;b[c++]=g}else{if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6}else{if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63}b[c++]=128|g>>6&63}b[c++]=128|g&63}}b[c]=0;return c-e}
function sa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}function ta(a){var b=sa(a)+1,c=C(b);D(a,na,c,b);return c}var na,E,ua,va,G,wa,H,I,J,xa=[],ya=[],za=[],Aa=[],Ba=[];function Ca(){var a=f.preRun.shift();xa.unshift(a)}var K=0,Da=null,L=null;f.preloadedImages={};f.preloadedAudios={};
function y(a){if(f.onAbort)f.onAbort(a);A(a);ka=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}function Ea(a){var b=M;return String.prototype.startsWith?b.startsWith(a):0===b.indexOf(a)}function Fa(){return Ea("data:application/octet-stream;base64,")}var M="demo.wasm";if(!Fa()){var Ga=M;M=f.locateFile?f.locateFile(Ga,w):w+Ga}
function Ha(){try{if(B)return new Uint8Array(B);if(x)return x(M);throw"both async and sync fetching of the wasm failed";}catch(a){y(a)}}function Ia(){return B||!u&&!v||"function"!==typeof fetch||Ea("file://")?Promise.resolve().then(Ha):fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ha()})}
function Ja(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(f);else{var c=b.$b;"number"===typeof c?void 0===b.Pb?J.get(c)():J.get(c)(b.Pb):c(void 0===b.Pb?null:b.Pb)}}}var Ka=[null,[],[]],La={},Ma=0;function Na(){for(var a=N.length-1;0<=a;--a)Oa(a);N=[];Pa=[]}var Pa=[];function Qa(){if(Ma&&Ra.Nb)for(var a=0;a<Pa.length;++a){var b=Pa[a];Pa.splice(a,1);--a;b.qc.apply(null,b.fc)}}var N=[];function Oa(a){var b=N[a];b.target.removeEventListener(b.Gb,b.Yb,b.Hb);N.splice(a,1)}
function O(a){function b(d){++Ma;Ra=a;Qa();a.Jb(d);Qa();--Ma}if(a.Ib)a.Yb=b,a.target.addEventListener(a.Gb,b,a.Hb),N.push(a),Sa||(Aa.push(Na),Sa=!0);else for(var c=0;c<N.length;++c)N[c].target==a.target&&N[c].Gb==a.Gb&&Oa(c--)}var Sa,Ra,Ta,Ua,Va,Wa,Xa,Ya,Za=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];function P(a){a=2<a?F(a):a;return Za[a]||("undefined"!==typeof document?document.querySelector(a):void 0)}
function $a(a){return 0>Za.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}function ab(a,b,c,d,e,h){Ta||(Ta=Q(164));a={target:P(a),Nb:!0,Gb:h,Ib:d,Jb:function(g){var m=Ta,n=m>>2;G[n]=g.location;G[n+1]=g.ctrlKey;G[n+2]=g.shiftKey;G[n+3]=g.altKey;G[n+4]=g.metaKey;G[n+5]=g.repeat;G[n+6]=g.charCode;G[n+7]=g.keyCode;G[n+8]=g.which;D(g.key||"",E,m+36,32);D(g.code||"",E,m+68,32);D(g.char||"",E,m+100,32);D(g.locale||"",E,m+132,32);J.get(d)(e,m,b)&&g.preventDefault()},Hb:c};O(a)}
function bb(a,b,c){a>>=2;G[a]=b.screenX;G[a+1]=b.screenY;G[a+2]=b.clientX;G[a+3]=b.clientY;G[a+4]=b.ctrlKey;G[a+5]=b.shiftKey;G[a+6]=b.altKey;G[a+7]=b.metaKey;ua[2*a+16]=b.button;ua[2*a+17]=b.buttons;G[a+9]=b.movementX;G[a+10]=b.movementY;c=$a(c);G[a+11]=b.clientX-c.left;G[a+12]=b.clientY-c.top}function R(a,b,c,d,e,h){Ua||(Ua=Q(64));a=P(a);O({target:a,Nb:"mousemove"!=h&&"mouseenter"!=h&&"mouseleave"!=h,Gb:h,Ib:d,Jb:function(g){g=g||event;bb(Ua,g,a);J.get(d)(e,Ua,b)&&g.preventDefault()},Hb:c})}
function cb(a,b,c,d,e){Va||(Va=Q(260));O({target:a,Gb:e,Ib:d,Jb:function(h){h=h||event;var g=Va,m=document.pointerLockElement||document.Rb||document.Tb||document.Sb;G[g>>2]=!!m;var n=m&&m.id?m.id:"";D(m?m==window?"#window":m==screen?"#screen":m&&m.nodeName?m.nodeName:"":"",E,g+4,128);D(n,E,g+132,128);J.get(d)(20,g,b)&&h.preventDefault()},Hb:c})}function db(a,b,c,d,e){O({target:a,Gb:e,Ib:d,Jb:function(h){h=h||event;J.get(d)(38,0,b)&&h.preventDefault()},Hb:c})}
function eb(a,b,c,d){Wa||(Wa=Q(36));a=P(a);O({target:a,Gb:"resize",Ib:d,Jb:function(e){e=e||event;if(e.target==a){var h=document.body;if(h){var g=Wa;G[g>>2]=e.detail;G[g+4>>2]=h.clientWidth;G[g+8>>2]=h.clientHeight;G[g+12>>2]=innerWidth;G[g+16>>2]=innerHeight;G[g+20>>2]=outerWidth;G[g+24>>2]=outerHeight;G[g+28>>2]=pageXOffset;G[g+32>>2]=pageYOffset;J.get(d)(10,g,b)&&e.preventDefault()}}},Hb:c})}
function fb(a,b,c,d,e,h){Xa||(Xa=Q(1684));a=P(a);O({target:a,Nb:"touchstart"==h||"touchend"==h,Gb:h,Ib:d,Jb:function(g){for(var m={},n=g.touches,q=0;q<n.length;++q){var p=n[q];m[p.identifier]=p}n=g.changedTouches;for(q=0;q<n.length;++q)p=n[q],p.bc=1,m[p.identifier]=p;n=g.targetTouches;for(q=0;q<n.length;++q)m[n[q].identifier].dc=1;n=Xa;p=n>>2;G[p+1]=g.ctrlKey;G[p+2]=g.shiftKey;G[p+3]=g.altKey;G[p+4]=g.metaKey;p+=5;var ib=$a(a),jb=0;for(q in m){var z=m[q];G[p]=z.identifier;G[p+1]=z.screenX;G[p+2]=
z.screenY;G[p+3]=z.clientX;G[p+4]=z.clientY;G[p+5]=z.pageX;G[p+6]=z.pageY;G[p+7]=z.bc;G[p+8]=z.dc;G[p+9]=z.clientX-ib.left;G[p+10]=z.clientY-ib.top;p+=13;if(31<++jb)break}G[n>>2]=jb;J.get(d)(e,n,b)&&g.preventDefault()},Hb:c})}function gb(a,b,c,d,e,h){a={target:P(a),Gb:h,Ib:d,Jb:function(g){g=g||event;J.get(d)(e,0,b)&&g.preventDefault()},Hb:c};O(a)}
function hb(a,b,c,d){Ya||(Ya=Q(96));O({target:a,Nb:!0,Gb:"wheel",Ib:d,Jb:function(e){e=e||event;var h=Ya;bb(h,e,a);I[h+64>>3]=e.deltaX;I[h+72>>3]=e.deltaY;I[h+80>>3]=e.deltaZ;G[h+88>>2]=e.deltaMode;J.get(d)(9,h,b)&&e.preventDefault()},Hb:c})}
function kb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,h){b.drawArraysInstancedANGLE(c,d,e,h)},a.drawElementsInstanced=function(c,d,e,h,g){b.drawElementsInstancedANGLE(c,d,e,h,g)})}
function lb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function mb(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}function nb(a){a.nc=a.getExtension("WEBGL_multi_draw")}
var ob=1,pb=[],S=[],qb=[],rb=[],sb=[],T=[],U=[],tb=[],V={},ub={};function W(a){vb||(vb=a)}function X(a){for(var b=ob++,c=a.length;c<b;c++)a[c]=null;return b}function wb(a){a||(a=xb);if(!a.ac){a.ac=!0;var b=a.Ob;kb(b);lb(b);mb(b);b.ic=b.getExtension("EXT_disjoint_timer_query");nb(b);(b.getSupportedExtensions()||[]).forEach(function(c){0>c.indexOf("lose_context")&&0>c.indexOf("debug")&&b.getExtension(c)})}}var vb,xb,yb=["default","low-power","high-performance"];
function zb(a,b,c,d){for(var e=0;e<a;e++){var h=Y[c](),g=h&&X(d);h?(h.name=g,d[g]=h):W(1282);G[b+4*e>>2]=g}}
function Ab(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Y.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Y.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:W(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)G[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W(1280);A("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:W(1280);A("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}G[b>>2]=c}else W(1281)}function Bb(a){var b=sa(a)+1,c=Q(b);D(a,E,c,b);return c}
function Cb(a,b,c,d,e){a-=5120;a=1==a?E:4==a?G:6==a?H:5==a||28922==a?wa:va;var h=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>h,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<h)+4-1&-4)>>h)}for(var Z=[],Y,Db=new Float32Array(288),Eb=0;288>Eb;++Eb)Z[Eb]=Db.subarray(0,Eb+1);ya.push({$b:function(){Fb()}});
var Ib={Z:function(){return 0},Za:function(){return 0},$a:function(){},J:function(){return"number"===typeof devicePixelRatio&&devicePixelRatio||1},ba:function(a,b,c){a=P(a);if(!a)return-4;a=$a(a);I[b>>3]=a.width;I[c>>3]=a.height;return 0},Wa:function(a,b,c){E.copyWithin(a,b,b+c)},Ha:function(a,b){function c(d){J.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},Xa:function(){y("OOM")},G:function(a,b,c){a=P(a);if(!a)return-4;a.width=b;a.height=c;return 0},S:function(a,b,c,d){ab(a,
b,c,d,2,"keydown");return 0},Q:function(a,b,c,d){ab(a,b,c,d,1,"keypress");return 0},R:function(a,b,c,d){ab(a,b,c,d,3,"keyup");return 0},Y:function(a,b,c,d){R(a,b,c,d,5,"mousedown");return 0},V:function(a,b,c,d){R(a,b,c,d,33,"mouseenter");return 0},U:function(a,b,c,d){R(a,b,c,d,34,"mouseleave");return 0},W:function(a,b,c,d){R(a,b,c,d,8,"mousemove");return 0},X:function(a,b,c,d){R(a,b,c,d,6,"mouseup");return 0},L:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.Rb||
document.body.Tb||document.body.Sb))return-1;a=P(a);if(!a)return-4;cb(a,b,c,d,"pointerlockchange");cb(a,b,c,d,"mozpointerlockchange");cb(a,b,c,d,"webkitpointerlockchange");cb(a,b,c,d,"mspointerlockchange");return 0},K:function(a,b,c,d){if(!document||!(document.body.requestPointerLock||document.body.Rb||document.body.Tb||document.body.Sb))return-1;a=P(a);if(!a)return-4;db(a,b,c,d,"pointerlockerror");db(a,b,c,d,"mozpointerlockerror");db(a,b,c,d,"webkitpointerlockerror");db(a,b,c,d,"mspointerlockerror");
return 0},Ta:function(a,b,c,d){eb(a,b,c,d);return 0},M:function(a,b,c,d){fb(a,b,c,d,25,"touchcancel");return 0},N:function(a,b,c,d){fb(a,b,c,d,23,"touchend");return 0},O:function(a,b,c,d){fb(a,b,c,d,24,"touchmove");return 0},P:function(a,b,c,d){fb(a,b,c,d,22,"touchstart");return 0},I:function(a,b,c,d){gb(a,b,c,d,31,"webglcontextlost");return 0},H:function(a,b,c,d){gb(a,b,c,d,32,"webglcontextrestored");return 0},T:function(a,b,c,d){a=P(a);return"undefined"!==typeof a.onwheel?(hb(a,b,c,d),0):-1},aa:function(a,
b){b>>=2;b={alpha:!!G[b],depth:!!G[b+1],stencil:!!G[b+2],antialias:!!G[b+3],premultipliedAlpha:!!G[b+4],preserveDrawingBuffer:!!G[b+5],powerPreference:yb[G[b+6]],failIfMajorPerformanceCaveat:!!G[b+7],cc:G[b+8],mc:G[b+9],Ub:G[b+10],Zb:G[b+11],oc:G[b+12],pc:G[b+13]};a=P(a);if(!a||b.Zb)b=0;else if(a=a.getContext("webgl",b)){var c=X(tb),d={lc:c,attributes:b,version:b.cc,Ob:a};a.canvas&&(a.canvas.ec=d);tb[c]=d;("undefined"===typeof b.Ub||b.Ub)&&wb(d);b=c}else b=0;return b},Ua:function(a,b){a=tb[a];b=F(b);
0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b&&kb(Y);"OES_vertex_array_object"==b&&lb(Y);"WEBGL_draw_buffers"==b&&mb(Y);"WEBGL_multi_draw"==b&&nb(Y);return!!a.Ob.getExtension(b)},la:function(a){a>>=2;for(var b=0;14>b;++b)G[a+b]=0;G[a]=G[a+1]=G[a+3]=G[a+4]=G[a+8]=G[a+10]=1},_a:function(a){xb=tb[a];f.hc=Y=xb&&xb.Ob;return!a||Y?0:-5},$:function(){return 0},Ya:function(a,b,c,d){a=La.kc(a);b=La.jc(a,b,c);G[d>>2]=b;return 0},Va:function(){},_:function(a,b,c,d){for(var e=0,h=0;h<c;h++){for(var g=
G[b+8*h>>2],m=G[b+(8*h+4)>>2],n=0;n<m;n++){var q=E[g+n],p=Ka[a];0===q||10===q?((1===a?ia:A)(ra(p,0)),p.length=0):p.push(q)}e+=m}G[d>>2]=e;return 0},y:function(a){Y.activeTexture(a)},w:function(a,b){Y.attachShader(S[a],U[b])},e:function(a,b){Y.bindBuffer(a,pb[b])},q:function(a,b){Y.bindFramebuffer(a,qb[b])},Ca:function(a,b){Y.bindRenderbuffer(a,rb[b])},f:function(a,b){Y.bindTexture(a,sb[b])},C:function(a,b,c,d){Y.blendColor(a,b,c,d)},D:function(a,b){Y.blendEquationSeparate(a,b)},E:function(a,b,c,d){Y.blendFuncSeparate(a,
b,c,d)},Fa:function(a,b,c,d){Y.bufferData(a,c?E.subarray(c,c+b):b,d)},x:function(a,b,c,d){Y.bufferSubData(a,b,E.subarray(d,d+c))},ha:function(a){Y.clear(a)},ka:function(a,b,c,d){Y.clearColor(a,b,c,d)},ja:function(a){Y.clearDepth(a)},ia:function(a){Y.clearStencil(a)},j:function(a,b,c,d){Y.colorMask(!!a,!!b,!!c,!!d)},qa:function(a){Y.compileShader(U[a])},za:function(a,b,c,d,e,h,g,m){Y.compressedTexImage2D(a,b,c,d,e,h,m?E.subarray(m,m+g):null)},xa:function(){var a=X(S),b=Y.createProgram();b.name=a;S[a]=
b;return a},ta:function(a){var b=X(U);U[b]=Y.createShader(a);return b},z:function(a){Y.cullFace(a)},na:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=pb[d];e&&(Y.deleteBuffer(e),e.name=0,pb[d]=null)}},h:function(a,b){for(var c=0;c<a;++c){var d=G[b+4*c>>2],e=qb[d];e&&(Y.deleteFramebuffer(e),e.name=0,qb[d]=null)}},t:function(a){if(a){var b=S[a];b?(Y.deleteProgram(b),b.name=0,S[a]=null,V[a]=null):W(1281)}},p:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=rb[d];e&&(Y.deleteRenderbuffer(e),
e.name=0,rb[d]=null)}},i:function(a){if(a){var b=U[a];b?(Y.deleteShader(b),U[a]=null):W(1281)}},ma:function(a,b){for(var c=0;c<a;c++){var d=G[b+4*c>>2],e=sb[d];e&&(Y.deleteTexture(e),e.name=0,sb[d]=null)}},m:function(a){Y.depthFunc(a)},l:function(a){Y.depthMask(!!a)},a:function(a){Y.disable(a)},F:function(a){Y.disableVertexAttribArray(a)},bb:function(a,b,c){Y.drawArrays(a,b,c)},cb:function(a,b,c,d){Y.drawElements(a,b,c,d)},b:function(a){Y.enable(a)},da:function(a){Y.enableVertexAttribArray(a)},A:function(a){Y.frontFace(a)},
Ga:function(a,b){zb(a,b,"createBuffer",pb)},Da:function(a,b){zb(a,b,"createRenderbuffer",rb)},Aa:function(a,b){zb(a,b,"createTexture",sb)},oa:function(a,b){return Y.getAttribLocation(S[a],F(b))},c:function(a,b){Ab(a,b)},va:function(a,b,c,d){a=Y.getProgramInfoLog(S[a]);null===a&&(a="(unknown error)");b=0<b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},u:function(a,b,c){if(c)if(a>=ob)W(1281);else{var d=V[a];if(d)if(35716==b)a=Y.getProgramInfoLog(S[a]),null===a&&(a="(unknown error)"),G[c>>2]=a.length+1;else if(35719==
b)G[c>>2]=d.Qb;else if(35722==b){if(-1==d.Kb){a=S[a];var e=Y.getProgramParameter(a,35721);for(b=d.Kb=0;b<e;++b)d.Kb=Math.max(d.Kb,Y.getActiveAttrib(a,b).name.length+1)}G[c>>2]=d.Kb}else if(35381==b){if(-1==d.Lb)for(a=S[a],e=Y.getProgramParameter(a,35382),b=d.Lb=0;b<e;++b)d.Lb=Math.max(d.Lb,Y.getActiveUniformBlockName(a,b).length+1);G[c>>2]=d.Lb}else G[c>>2]=Y.getProgramParameter(S[a],b);else W(1282)}else W(1281)},pa:function(a,b,c,d){a=Y.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<
b&&d?D(a,E,d,b):0;c&&(G[c>>2]=b)},r:function(a,b,c){c?35716==b?(a=Y.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),G[c>>2]=a?a.length+1:0):35720==b?(a=Y.getShaderSource(U[a]),G[c>>2]=a?a.length+1:0):G[c>>2]=Y.getShaderParameter(U[a],b):W(1281)},Ka:function(a){if(ub[a])return ub[a];switch(a){case 7939:var b=Y.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));b=Bb(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Y.getParameter(a))||W(1280);b=Bb(b);break;
case 7938:b=Bb("OpenGL ES 2.0 ("+Y.getParameter(7938)+")");break;case 35724:b=Y.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=Bb(b);break;default:return W(1280),0}return ub[a]=b},s:function(a,b){b=F(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=V[a]&&V[a].Xb[b])&&0<=c&&c<a[0]?a[1]+c:-1},wa:function(a){Y.linkProgram(S[a]);
var b=S[a];a=V[a]={Xb:{},Qb:0,Kb:-1,Lb:-1};for(var c=a.Xb,d=Y.getProgramParameter(b,35718),e=0;e<d;++e){var h=Y.getActiveUniform(b,e),g=h.name;a.Qb=Math.max(a.Qb,g.length+1);"]"==g.slice(-1)&&(g=g.slice(0,g.lastIndexOf("[")));var m=Y.getUniformLocation(b,g);if(m){var n=X(T);c[g]=[h.size,n];T[n]=m;for(var q=1;q<h.size;++q)m=Y.getUniformLocation(b,g+"["+q+"]"),n=X(T),T[n]=m}}},B:function(a,b){Y.polygonOffset(a,b)},Ba:function(a,b,c,d){Y.renderbufferStorage(a,b,c,d)},n:function(a,b,c,d){Y.scissor(a,
b,c,d)},sa:function(a,b,c,d){for(var e="",h=0;h<b;++h){var g=d?G[d+4*h>>2]:-1;e+=F(G[c+4*h>>2],0>g?void 0:g)}Y.shaderSource(U[a],e)},Ja:function(a,b,c){Y.stencilFunc(a,b,c)},ga:function(a,b,c,d){Y.stencilFuncSeparate(a,b,c,d)},k:function(a){Y.stencilMask(a)},Ia:function(a,b,c){Y.stencilOp(a,b,c)},fa:function(a,b,c,d){Y.stencilOpSeparate(a,b,c,d)},ya:function(a,b,c,d,e,h,g,m,n){Y.texImage2D(a,b,c,d,e,h,g,m,n?Cb(m,g,d,e,n):null)},d:function(a,b,c){Y.texParameteri(a,b,c)},ca:function(a,b,c){if(288>=
b)for(var d=Z[b-1],e=0;e<b;++e)d[e]=H[c+4*e>>2];else d=H.subarray(c>>2,c+4*b>>2);Y.uniform1fv(T[a],d)},ua:function(a,b){Y.uniform1i(T[a],b)},gb:function(a,b,c){if(144>=b)for(var d=Z[2*b-1],e=0;e<2*b;e+=2)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2];else d=H.subarray(c>>2,c+8*b>>2);Y.uniform2fv(T[a],d)},fb:function(a,b,c){if(96>=b)for(var d=Z[3*b-1],e=0;e<3*b;e+=3)d[e]=H[c+4*e>>2],d[e+1]=H[c+(4*e+4)>>2],d[e+2]=H[c+(4*e+8)>>2];else d=H.subarray(c>>2,c+12*b>>2);Y.uniform3fv(T[a],d)},eb:function(a,b,c){if(72>=
b){var d=Z[4*b-1],e=H;c>>=2;for(var h=0;h<4*b;h+=4){var g=c+h;d[h]=e[g];d[h+1]=e[g+1];d[h+2]=e[g+2];d[h+3]=e[g+3]}}else d=H.subarray(c>>2,c+16*b>>2);Y.uniform4fv(T[a],d)},db:function(a,b,c,d){if(18>=b){var e=Z[16*b-1],h=H;d>>=2;for(var g=0;g<16*b;g+=16){var m=d+g;e[g]=h[m];e[g+1]=h[m+1];e[g+2]=h[m+2];e[g+3]=h[m+3];e[g+4]=h[m+4];e[g+5]=h[m+5];e[g+6]=h[m+6];e[g+7]=h[m+7];e[g+8]=h[m+8];e[g+9]=h[m+9];e[g+10]=h[m+10];e[g+11]=h[m+11];e[g+12]=h[m+12];e[g+13]=h[m+13];e[g+14]=h[m+14];e[g+15]=h[m+15]}}else e=
H.subarray(d>>2,d+64*b>>2);Y.uniformMatrix4fv(T[a],!!c,e)},g:function(a){Y.useProgram(S[a])},ab:function(a,b){Y.vertexAttribDivisor(a,b)},ea:function(a,b,c,d,e,h){Y.vertexAttribPointer(a,b,c,!!d,e,h)},o:function(a,b,c,d){Y.viewport(a,b,c,d)},Sa:function(){f.Vb=function(a){0!=Gb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Vb)},Ra:function(){f.Wb=function(a){a=a.clipboardData.getData("text");ma([a])};window.addEventListener("paste",f.Wb)},Pa:function(){var a=
document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){Hb()});document.body.append(a)},Oa:function(){document.getElementById("_sokol_app_input_element").focus()},hb:function(a){a=F(a);f.Mb=document.getElementById(a);f.Mb||console.log("sokol_app.h: invalid target:"+a);f.Mb.requestPointerLock||console.log("sokol_app.h: target doesn't support requestPointerLock:"+a)},Ma:function(){window.removeEventListener("beforeunload",
f.Vb)},La:function(){window.removeEventListener("paste",f.Wb)},Qa:function(){f.Mb&&f.Mb.requestPointerLock&&f.Mb.requestPointerLock()},Na:function(){document.getElementById("_sokol_app_input_element").blur()},Ea:function(a){a=F(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=1;b.value=
a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},ra:function(){return navigator.userAgent.includes("Macintosh")?1:0},v:function(){return performance.now()}};
(function(){function a(e){f.asm=e.exports;ja=f.asm.ib;e=ja.buffer;f.HEAP8=na=new Int8Array(e);f.HEAP16=ua=new Int16Array(e);f.HEAP32=G=new Int32Array(e);f.HEAPU8=E=new Uint8Array(e);f.HEAPU16=va=new Uint16Array(e);f.HEAPU32=wa=new Uint32Array(e);f.HEAPF32=H=new Float32Array(e);f.HEAPF64=I=new Float64Array(e);J=f.asm.jb;K--;f.monitorRunDependencies&&f.monitorRunDependencies(K);0==K&&(null!==Da&&(clearInterval(Da),Da=null),L&&(e=L,L=null,e()))}function b(e){a(e.instance)}function c(e){return Ia().then(function(h){return WebAssembly.instantiate(h,
d)}).then(e,function(h){A("failed to asynchronously prepare wasm: "+h);y(h)})}var d={a:Ib};K++;f.monitorRunDependencies&&f.monitorRunDependencies(K);if(f.instantiateWasm)try{return f.instantiateWasm(d,a)}catch(e){return A("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return B||"function"!==typeof WebAssembly.instantiateStreaming||Fa()||Ea("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,
d).then(b,function(h){A("wasm streaming compile failed: "+h);A("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();var Fb=f.___wasm_call_ctors=function(){return(Fb=f.___wasm_call_ctors=f.asm.kb).apply(null,arguments)},Hb=f.__sapp_emsc_notify_keyboard_hidden=function(){return(Hb=f.__sapp_emsc_notify_keyboard_hidden=f.asm.lb).apply(null,arguments)};f.__sapp_emsc_onpaste=function(){return(f.__sapp_emsc_onpaste=f.asm.mb).apply(null,arguments)};
var Gb=f.__sapp_html5_get_ask_leave_site=function(){return(Gb=f.__sapp_html5_get_ask_leave_site=f.asm.nb).apply(null,arguments)};f.___em_js__sapp_js_create_textfield=function(){return(f.___em_js__sapp_js_create_textfield=f.asm.ob).apply(null,arguments)};f.___em_js__sapp_js_focus_textfield=function(){return(f.___em_js__sapp_js_focus_textfield=f.asm.pb).apply(null,arguments)};f.___em_js__sapp_js_unfocus_textfield=function(){return(f.___em_js__sapp_js_unfocus_textfield=f.asm.qb).apply(null,arguments)};
f.___em_js__sapp_js_add_hook_beforeunload=function(){return(f.___em_js__sapp_js_add_hook_beforeunload=f.asm.rb).apply(null,arguments)};f.___em_js__sapp_js_remove_hook_beforeunload=function(){return(f.___em_js__sapp_js_remove_hook_beforeunload=f.asm.sb).apply(null,arguments)};f.___em_js__sapp_js_add_hook_clipboard=function(){return(f.___em_js__sapp_js_add_hook_clipboard=f.asm.tb).apply(null,arguments)};
f.___em_js__sapp_js_remove_hook_clipboard=function(){return(f.___em_js__sapp_js_remove_hook_clipboard=f.asm.ub).apply(null,arguments)};f.___em_js__sapp_js_write_clipboard=function(){return(f.___em_js__sapp_js_write_clipboard=f.asm.vb).apply(null,arguments)};f.___em_js__sapp_js_pointer_init=function(){return(f.___em_js__sapp_js_pointer_init=f.asm.wb).apply(null,arguments)};f.___em_js__sapp_js_request_pointerlock=function(){return(f.___em_js__sapp_js_request_pointerlock=f.asm.xb).apply(null,arguments)};
f.___em_js__sapp_js_exit_pointerlock=function(){return(f.___em_js__sapp_js_exit_pointerlock=f.asm.yb).apply(null,arguments)};f._main=function(){return(f._main=f.asm.zb).apply(null,arguments)};var Q=f._malloc=function(){return(Q=f._malloc=f.asm.Ab).apply(null,arguments)};f.___em_js__stm_js_perfnow=function(){return(f.___em_js__stm_js_perfnow=f.asm.Bb).apply(null,arguments)};f.___em_js__simgui_js_is_osx=function(){return(f.___em_js__simgui_js_is_osx=f.asm.Cb).apply(null,arguments)};
var oa=f.stackSave=function(){return(oa=f.stackSave=f.asm.Db).apply(null,arguments)},pa=f.stackRestore=function(){return(pa=f.stackRestore=f.asm.Eb).apply(null,arguments)},C=f.stackAlloc=function(){return(C=f.stackAlloc=f.asm.Fb).apply(null,arguments)},Jb;function ha(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}L=function Kb(){Jb||Lb();Jb||(L=Kb)};
function Lb(a){function b(){if(!Jb&&(Jb=!0,f.calledRun=!0,!ka)){Ja(ya);Ja(za);if(f.onRuntimeInitialized)f.onRuntimeInitialized();if(Mb){var c=a,d=f._main;c=c||[];var e=c.length+1,h=C(4*(e+1));G[h>>2]=ta(aa);for(var g=1;g<e;g++)G[(h>>2)+g]=ta(c[g-1]);G[(h>>2)+e]=0;try{var m=d(e,h);if(!noExitRuntime||0!==m){if(!noExitRuntime){if(f.onExit)f.onExit(m);ka=!0}t(m,new ha(m))}}catch(n){n instanceof ha||("unwind"==n?noExitRuntime=!0:((c=n)&&"object"===typeof n&&n.stack&&(c=[n,n.stack]),A("exception thrown: "+
c),t(1,n)))}finally{}}if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;)c=f.postRun.shift(),Ba.unshift(c);Ja(Ba)}}a=a||r;if(!(0<K)){if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)Ca();Ja(xa);0<K||(f.setStatus?(f.setStatus("Running..."),setTimeout(function(){setTimeout(function(){f.setStatus("")},1);b()},1)):b())}}f.run=Lb;if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();
var Mb=!0;f.noInitialRun&&(Mb=!1);noExitRuntime=!0;Lb();
